# Generated by Django 2.2.7 on 2019-11-08 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course_number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_date', models.DateField()),
                ('first_day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک شسنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهار شنبه')], default='0')),
                ('second_day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک شسنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهار شنبه')], default='0')),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
