# Generated by Django 2.2.7 on 2019-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaneh', '0004_course_first_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(choices=[('0', 'شنبه'), ('1', 'یک سنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه')], default='0'),
        ),
    ]
