# Generated by Django 2.2.7 on 2019-11-08 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samaneh', '0005_course_second_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک شسنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهار شنبه')], default='0'),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک شسنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهار شنبه')], default='0'),
        ),
    ]
